name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go vet ./...
        go test -v ./...
      
    - name: Format
      run: |
        result=$(gofmt -l . | wc -l)
        if [ $result -ne 0 ]; then
          exit 1
        fi
